orbs:
  react: 'thefrontside/react@0.2.0'
version: 2.1

# Define the jobs we want to run for this project
jobs:
  deploy_webapp:
    type: approval
    docker:
      - image: arvindr226/alpine-ssh
    steps:
      - add_ssh_keys:
          fingerprints:
            - "c8:d1:32:47:a7:13:6f:63:ba:4e:5c:3e:14:50:5a:77"
      - run: ssh -oStrictHostKeyChecking=no -v $DROPLET_USER@$DROPLET_IP "./deploy_react_webapp.sh"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - deploy_webapp:
          filters:
            branches:
              only:
                - master

  push:
    jobs:
      - react/install
      - react/eslint:
          requires:
            - react/install
      - react/test:
          requires:
            - react/install
      - react/coverage:
          requires:
            - react/install
